const STORAGE_KEY='plateQuest.v3';
const MAP_URLS=['https://code.highcharts.com/mapdata/countries/us/us-all.geo.json','https://code.highcharts.com/mapdata/countries/ca/ca-all.geo.json','https://code.highcharts.com/mapdata/countries/mx/mx-all.geo.json'];
let jurisdictions=[],selectedId=null,position=null,map=null,mapLayer=null,marker=null,boundaries=[];
let state=loadState(); const $=id=>document.getElementById(id);
function defaults(){return{activeTrip:null,trips:[],currentJurisdictionId:null,lastPlayer:'Family'};}
function loadState(){try{return{...defaults(),...(JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem('plateQuest.v2'))||{})};}catch{return defaults();}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();}
function trip(){return state.trips.find(t=>t.id===state.activeTrip)||null;}
function uuid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function haversine(a,b){const r=3958.8,d=Math.PI/180,dlat=(b.lat-a.lat)*d,dlon=(b.lon-a.lon)*d,x=Math.sin(dlat/2)**2+Math.cos(a.lat*d)*Math.cos(b.lat*d)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(x));}
function points(m){return m<1?10:Math.round(20*Math.sqrt(m));}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2300);}
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function matchJurisdiction(feature){const p=feature.properties||{},key=(p['hc-key']||'').toUpperCase();let j=jurisdictions.find(x=>x.id===key);if(j)return j;const name=p.name||p.NAME_1||p['woe-name'];return jurisdictions.find(x=>normalize(x.name)===normalize(name));}
function pointInRing(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1],hit=((yi>point.lat)!=(yj>point.lat))&&(point.lon<(xj-xi)*(point.lat-yi)/(yj-yi)+xi);if(hit)inside=!inside;}return inside;}
function pointInGeometry(point,g){if(!g)return false;const poly=p=>pointInRing(point,p[0])&&!p.slice(1).some(r=>pointInRing(point,r));return g.type==='Polygon'?poly(g.coordinates):g.type==='MultiPolygon'?g.coordinates.some(poly):false;}
function detectJurisdiction(pos){const f=boundaries.find(x=>pointInGeometry(pos,x.geometry));return f?matchJurisdiction(f):null;}
function anchor(){if(position)return position;const j=jurisdictions.find(x=>x.id===state.currentJurisdictionId);return j?.lat!=null?{lat:j.lat,lon:j.lon}:null;}
function render(){const t=trip(),seen=new Set(t?.sightings.map(s=>s.jurisdictionId)||[]),miles=t?.sightings.reduce((n,s)=>n+s.distance,0)||0,score=t?.sightings.reduce((n,s)=>n+s.points,0)||0,current=jurisdictions.find(j=>j.id===state.currentJurisdictionId);$('tripName').textContent=t?t.name:'No active trip';$('endTripButton').hidden=!t;$('plateCount').textContent=t?.sightings.length||0;$('distanceTotal').textContent=Math.round(miles).toLocaleString();$('pointTotal').textContent=score.toLocaleString();$('completionTotal').textContent=`${Math.round(seen.size/jurisdictions.length*100)||0}%`;$('locationText').textContent=current?`${current.name}${position?` · GPS ±${Math.round(position.accuracy)} m`:''}`:'Set your current location to begin scoring plates.';$('currentJurisdiction').value=state.currentJurisdictionId||'';renderGroups(seen);renderCollected(t);styleMap(seen);}
function renderGroups(seen){const q=$('plateSearch').value.trim().toLowerCase(),groups=['United States','Canada','Mexico','Territories','Special'];$('countryGroups').innerHTML=groups.map(region=>{const items=jurisdictions.filter(j=>j.region===region&&(!q||`${j.name} ${j.abbr}`.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));if(!items.length)return'';return `<section class="country-group"><h3>${region}<span>${items.filter(j=>seen.has(j.id)).length}/${items.length}</span></h3><div class="jurisdiction-grid">${items.map(j=>`<button class="jurisdiction ${seen.has(j.id)?'collected':''}" data-id="${j.id}" ${seen.has(j.id)?'disabled':''}><span class="mini-plate">${esc(j.abbr)}</span><strong>${esc(j.name)}</strong></button>`).join('')}</div></section>`}).join('');}
function renderCollected(t){if(!t?.sightings.length){$('collectedList').className='empty-state';$('collectedList').textContent='Start a trip and add the first plate.';return;}$('collectedList').className='';$('collectedList').innerHTML=t.sightings.slice().reverse().map(s=>`<div class="collected-item"><span><strong>${esc(s.name)}</strong><br><small>${Math.round(s.distance)} miles · ${esc(s.player)}${s.note?` · ${esc(s.note)}`:''}</small></span><strong>${s.points} pts</strong></div>`).join('');}
function populateLocation(){const a=jurisdictions.filter(j=>j.lat!=null&&j.region!=='Special').sort((x,y)=>x.name.localeCompare(y.name));$('currentJurisdiction').innerHTML='<option value="">Choose state, province, or territory</option>'+a.map(j=>`<option value="${j.id}">${esc(j.name)} (${esc(j.abbr)})</option>`).join('');}
function startTrip(name){state.trips.push({id:uuid(),name,startedAt:new Date().toISOString(),sightings:[]});state.activeTrip=state.trips.at(-1).id;persist();}
function openSighting(id){const t=trip();if(!t){$('tripDialog').showModal();return;}if(t.sightings.some(s=>s.jurisdictionId===id))return;const j=jurisdictions.find(x=>x.id===id);if(!j)return;selectedId=id;const a=anchor(),d=j.fixedPoints?0:a&&j.lat!=null?haversine(a,{lat:j.lat,lon:j.lon}):0,p=j.fixedPoints||points(d);$('platePreview').textContent=j.abbr;$('sightingTitle').textContent=`Add ${j.name}`;$('sightingDetails').textContent=a?`Estimated distance: ${Math.round(d).toLocaleString()} miles · ${p} points`:'No location set · 10 points';$('playerInput').value=state.lastPlayer||'Family';$('noteInput').value='';$('sightingDialog').showModal();}
function saveSighting(){const t=trip(),j=jurisdictions.find(x=>x.id===selectedId);if(!t||!j)return;const a=anchor(),d=j.fixedPoints?0:a&&j.lat!=null?haversine(a,{lat:j.lat,lon:j.lon}):0,p=j.fixedPoints||points(d),player=$('playerInput').value.trim()||'Family';state.lastPlayer=player;t.sightings.push({id:uuid(),jurisdictionId:j.id,name:j.name,distance:d,points:p,player,note:$('noteInput').value.trim(),lat:position?.lat??null,lon:position?.lon??null,sightedAt:new Date().toISOString()});$('sightingDialog').close();persist();toast(`${j.name} collected`);}
function styleMap(seen){if(!mapLayer)return;mapLayer.eachLayer(l=>{const j=matchJurisdiction(l.feature);l.setStyle({color:'#60758f',weight:1,fillOpacity:.72,fillColor:j&&seen.has(j.id)?'#e9b949':j&&state.currentJurisdictionId===j.id?'#35c3a5':'#263b55'});});}
async function loadMap(){map=L.map('map',{zoomControl:true,attributionControl:false,minZoom:2}).setView([44,-98],3);try{const sets=await Promise.all(MAP_URLS.map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('boundary download failed');return r.json();}));boundaries=sets.flatMap(x=>x.features||[]);mapLayer=L.geoJSON({type:'FeatureCollection',features:boundaries},{style:{color:'#60758f',weight:1,fillColor:'#263b55',fillOpacity:.72},onEachFeature:(f,l)=>{const j=matchJurisdiction(f);if(j){l.bindTooltip(j.name);l.on('click',()=>openSighting(j.id));}}}).addTo(map);map.fitBounds(mapLayer.getBounds(),{padding:[8,8]});$('mapStatus').textContent='Tap a state, province, or Mexican state to record its plate.';render();}catch(e){$('mapStatus').textContent='Map boundaries could not load. The country-sorted plate list remains fully playable.';}}
function locate(){if(!navigator.geolocation){toast('Geolocation unavailable');return;}$('locationText').textContent='Locating…';navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy};const found=detectJurisdiction(position);if(found)state.currentJurisdictionId=found.id;if(map){marker&&marker.remove();marker=L.circleMarker([position.lat,position.lon],{radius:8,color:'#fff',weight:3,fillColor:'#ff5d73',fillOpacity:1}).addTo(map);map.setView([position.lat,position.lon],7);}persist();toast(found?`Location: ${found.name}`:'Location found; choose jurisdiction manually');},e=>{render();toast(e.message);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
function exportData(){const b=new Blob([JSON.stringify({format:'plate-quest-backup',version:3,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='plate-quest-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function init(){const r=await fetch('./data/jurisdictions.json');jurisdictions=await r.json();populateLocation();render();updateNetwork();loadMap();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');}
function updateNetwork(){$('networkStatus').textContent=navigator.onLine?'Online':'Offline · saved locally';}
$('newTripButton').onclick=()=>$('tripDialog').showModal();$('tripForm').onsubmit=e=>{e.preventDefault();startTrip($('tripNameInput').value.trim());$('tripDialog').close();e.target.reset();};$('sightingForm').onsubmit=e=>{e.preventDefault();saveSighting();};document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c)$(c.dataset.close).close();const p=e.target.closest('[data-id]');if(p&&!p.disabled)openSighting(p.dataset.id);});$('currentJurisdiction').onchange=e=>{position=null;state.currentJurisdictionId=e.target.value||null;persist();};$('locateButton').onclick=locate;$('fitMapButton').onclick=()=>mapLayer&&map.fitBounds(mapLayer.getBounds());$('plateSearch').oninput=render;$('endTripButton').onclick=()=>{const t=trip();if(t&&confirm(`End ${t.name}?`)){t.endedAt=new Date().toISOString();state.activeTrip=null;persist();}};$('exportButton').onclick=exportData;$('clearButton').onclick=()=>{if(confirm('Delete all Plate Quest data?')){localStorage.removeItem(STORAGE_KEY);state=defaults();position=null;persist();}};addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);init();