const STORAGE_KEY='plateQuest.v4';
const MAP_URLS=['https://code.highcharts.com/mapdata/countries/us/us-all.geo.json','https://code.highcharts.com/mapdata/countries/ca/ca-all.geo.json','https://code.highcharts.com/mapdata/countries/mx/mx-all.geo.json'];
let jurisdictions=[],selectedId=null,position=null,boundaries=[],locating=false;
let state=loadState();const $=id=>document.getElementById(id);
function defaults(){return{activeTrip:null,trips:[],currentJurisdictionId:null,lastPlayer:'Family'};}
function loadState(){try{return{...defaults(),...(JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem('plateQuest.v3'))||JSON.parse(localStorage.getItem('plateQuest.v2'))||{})};}catch{return defaults();}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();}
function trip(){return state.trips.find(t=>t.id===state.activeTrip)||null;}
function uuid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function haversine(a,b){const r=3958.8,d=Math.PI/180,dlat=(b.lat-a.lat)*d,dlon=(b.lon-a.lon)*d,x=Math.sin(dlat/2)**2+Math.cos(a.lat*d)*Math.cos(b.lat*d)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(x));}
function points(m){return m<1?10:Math.round(20*Math.sqrt(m));}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function matchJurisdiction(feature){const p=feature.properties||{},key=(p['hc-key']||'').toUpperCase();let j=jurisdictions.find(x=>x.id===key);if(j)return j;const name=p.name||p.NAME_1||p['woe-name'];return jurisdictions.find(x=>normalize(x.name)===normalize(name));}
function pointInRing(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];if(((yi>point.lat)!=(yj>point.lat))&&(point.lon<(xj-xi)*(point.lat-yi)/(yj-yi)+xi))inside=!inside;}return inside;}
function pointInGeometry(point,g){if(!g)return false;const poly=p=>pointInRing(point,p[0])&&!p.slice(1).some(r=>pointInRing(point,r));return g.type==='Polygon'?poly(g.coordinates):g.type==='MultiPolygon'?g.coordinates.some(poly):false;}
function detectByBoundary(pos){const f=boundaries.find(x=>pointInGeometry(pos,x.geometry));return f?matchJurisdiction(f):null;}
function anchor(){if(position)return position;const j=jurisdictions.find(x=>x.id===state.currentJurisdictionId);return j?.lat!=null?{lat:j.lat,lon:j.lon}:null;}
function project(lat,lon){const x=(lon+170)/120*1000,y=(82-lat)/68*620;return{x:Math.max(18,Math.min(982,x)),y:Math.max(18,Math.min(602,y))};}
function render(){const t=trip(),seen=new Set(t?.sightings.map(s=>s.jurisdictionId)||[]),miles=t?.sightings.reduce((n,s)=>n+s.distance,0)||0,score=t?.sightings.reduce((n,s)=>n+s.points,0)||0,current=jurisdictions.find(j=>j.id===state.currentJurisdictionId);$('tripName').textContent=t?t.name:'No active trip';$('endTripButton').hidden=!t;$('plateCount').textContent=t?.sightings.length||0;$('distanceTotal').textContent=Math.round(miles).toLocaleString();$('pointTotal').textContent=score.toLocaleString();$('completionTotal').textContent=`${Math.round(seen.size/jurisdictions.length*100)||0}%`;$('locationText').textContent=current?`${current.name}${position?` · GPS ±${Math.round(position.accuracy)} m`:''}`:'Set your current location to begin scoring plates.';$('currentJurisdiction').value=state.currentJurisdictionId||'';$('locationProgress').hidden=!locating;renderGroups(seen);renderCollected(t);renderMap(seen);}
function renderGroups(seen){const q=$('plateSearch').value.trim().toLowerCase(),groups=['United States','Canada','Mexico','Territories','Special'];$('countryGroups').innerHTML=groups.map(region=>{const items=jurisdictions.filter(j=>j.region===region&&(!q||`${j.name} ${j.abbr}`.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));if(!items.length)return'';return `<section class="country-group"><h3>${region}<span>${items.filter(j=>seen.has(j.id)).length}/${items.length}</span></h3><div class="jurisdiction-grid">${items.map(j=>`<button class="jurisdiction ${seen.has(j.id)?'collected':''}" data-id="${j.id}" ${seen.has(j.id)?'disabled':''}><span class="mini-plate">${esc(j.abbr)}</span><strong>${esc(j.name)}</strong></button>`).join('')}</div></section>`}).join('');}
function renderCollected(t){if(!t?.sightings.length){$('collectedList').className='empty-state';$('collectedList').textContent='Start a trip and add the first plate.';return;}$('collectedList').className='';$('collectedList').innerHTML=t.sightings.slice().reverse().map(s=>`<div class="collected-item"><span><strong>${esc(s.name)}</strong><br><small>${Math.round(s.distance)} miles · ${esc(s.player)}${s.note?` · ${esc(s.note)}`:''}</small></span><strong>${s.points} pts</strong></div>`).join('');}
function renderMap(seen){const svg=$('mapSvg');if(!svg)return;const nodes=jurisdictions.filter(j=>j.lat!=null&&j.lon!=null&&j.region!=='Special').map(j=>{const p=project(j.lat,j.lon),cls=`map-node${seen.has(j.id)?' collected':''}${state.currentJurisdictionId===j.id?' current':''}`;return `<g class="${cls}" data-map-id="${j.id}" tabindex="0" role="button" aria-label="${esc(j.name)}"><title>${esc(j.name)}</title><circle cx="${p.x}" cy="${p.y}" r="${j.region==='United States'?10:9}"></circle><text x="${p.x}" y="${p.y}">${esc(j.abbr)}</text></g>`}).join('');let gps='';if(position){const p=project(position.lat,position.lon);gps=`<circle class="gps-marker" cx="${p.x}" cy="${p.y}" r="8"><title>Your GPS position</title></circle>`;}svg.innerHTML=`<path class="continent" d="M75 85 L180 35 L335 55 L420 110 L510 115 L620 150 L705 225 L675 295 L590 330 L520 370 L455 395 L390 365 L300 330 L240 275 L165 245 L95 185 Z"></path><path class="continent" d="M385 360 L510 355 L600 395 L655 460 L620 540 L550 585 L485 540 L445 465 Z"></path><text class="country-label" x="350" y="170">CANADA</text><text class="country-label" x="350" y="315">UNITED STATES</text><text class="country-label" x="500" y="505">MEXICO</text>${nodes}${gps}`;$('mapStatus').textContent=boundaries.length?'Map ready. GPS uses real borders; tap a jurisdiction to record its plate.':'Map ready in offline mode. GPS will use online state lookup when border data is unavailable.';}
function populateLocation(){const a=jurisdictions.filter(j=>j.lat!=null&&j.region!=='Special').sort((x,y)=>x.name.localeCompare(y.name));$('currentJurisdiction').innerHTML='<option value="">Choose state, province, or territory</option>'+a.map(j=>`<option value="${j.id}">${esc(j.name)} (${esc(j.abbr)})</option>`).join('');}
function startTrip(name){state.trips.push({id:uuid(),name,startedAt:new Date().toISOString(),sightings:[]});state.activeTrip=state.trips.at(-1).id;persist();}
function openSighting(id){const t=trip();if(!t){$('tripDialog').showModal();return;}if(t.sightings.some(s=>s.jurisdictionId===id))return;const j=jurisdictions.find(x=>x.id===id);if(!j)return;selectedId=id;const a=anchor(),d=j.fixedPoints?0:a&&j.lat!=null?haversine(a,{lat:j.lat,lon:j.lon}):0,p=j.fixedPoints||points(d);$('platePreview').textContent=j.abbr;$('sightingTitle').textContent=`Add ${j.name}`;$('sightingDetails').textContent=a?`Estimated distance: ${Math.round(d).toLocaleString()} miles · ${p} points`:'No location set · 10 points';$('playerInput').value=state.lastPlayer||'Family';$('noteInput').value='';$('sightingDialog').showModal();}
function saveSighting(){const t=trip(),j=jurisdictions.find(x=>x.id===selectedId);if(!t||!j)return;const a=anchor(),d=j.fixedPoints?0:a&&j.lat!=null?haversine(a,{lat:j.lat,lon:j.lon}):0,p=j.fixedPoints||points(d),player=$('playerInput').value.trim()||'Family';state.lastPlayer=player;t.sightings.push({id:uuid(),jurisdictionId:j.id,name:j.name,distance:d,points:p,player,note:$('noteInput').value.trim(),lat:position?.lat??null,lon:position?.lon??null,sightedAt:new Date().toISOString()});$('sightingDialog').close();persist();toast(`${j.name} collected`);}
async function detectByReverseGeocode(pos){try{const u=`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${encodeURIComponent(pos.lat)}&longitude=${encodeURIComponent(pos.lon)}&localityLanguage=en`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)return null;const d=await r.json();const code=(d.principalSubdivisionCode||'').toUpperCase(),name=d.principalSubdivision;return jurisdictions.find(j=>j.id===code||normalize(j.name)===normalize(name))||null;}catch{return null;}}
async function applyPosition(coords){position={lat:coords.latitude,lon:coords.longitude,accuracy:coords.accuracy};let found=detectByBoundary(position);if(!found)found=await detectByReverseGeocode(position);if(found)state.currentJurisdictionId=found.id;persist();return found;}
function locate(){if(!navigator.geolocation){toast('Geolocation is unavailable in this browser');return;}if(locating)return;locating=true;render();let best=null,finished=false;const finish=async(reason)=>{if(finished)return;finished=true;clearTimeout(timer);watchId!=null&&navigator.geolocation.clearWatch(watchId);locating=false;if(!best){render();toast(reason||'No GPS reading received');return;}const found=await applyPosition(best.coords);toast(found?`Location confirmed: ${found.name} · ±${Math.round(best.coords.accuracy)} m`:`GPS found · ±${Math.round(best.coords.accuracy)} m. Choose the jurisdiction manually.`);};const watchId=navigator.geolocation.watchPosition(p=>{if(!best||p.coords.accuracy<best.coords.accuracy)best=p;$('locationText').textContent=`GPS reading ±${Math.round(p.coords.accuracy)} m…`;if(p.coords.accuracy<=100)finish();},e=>finish(`Location error: ${e.message}`),{enableHighAccuracy:true,maximumAge:0,timeout:20000});const timer=setTimeout(()=>finish('GPS timed out'),12000);}
async function loadBoundaries(){try{const sets=await Promise.all(MAP_URLS.map(async u=>{const r=await fetch(u,{cache:'force-cache'});if(!r.ok)throw Error('boundary download failed');return r.json();}));boundaries=sets.flatMap(x=>x.features||[]);render();}catch{boundaries=[];render();}}
function exportData(){const b=new Blob([JSON.stringify({format:'plate-quest-backup',version:4,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='plate-quest-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function init(){try{const r=await fetch('./data/jurisdictions.json');if(!r.ok)throw Error('Game data failed to load');jurisdictions=await r.json();populateLocation();render();updateNetwork();loadBoundaries();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');}catch(e){$('mapStatus').textContent=e.message;toast(e.message);}}
function updateNetwork(){$('networkStatus').textContent=navigator.onLine?'Online':'Offline · saved locally';}
$('newTripButton').onclick=()=>$('tripDialog').showModal();$('tripForm').onsubmit=e=>{e.preventDefault();const name=$('tripNameInput').value.trim();if(!name)return;startTrip(name);$('tripDialog').close();e.target.reset();};$('sightingForm').onsubmit=e=>{e.preventDefault();saveSighting();};document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c)$(c.dataset.close).close();const p=e.target.closest('[data-id]');if(p&&!p.disabled)openSighting(p.dataset.id);const m=e.target.closest('[data-map-id]');if(m)openSighting(m.dataset.mapId);});document.addEventListener('keydown',e=>{const m=e.target.closest?.('[data-map-id]');if(m&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openSighting(m.dataset.mapId);}});$('currentJurisdiction').onchange=e=>{position=null;state.currentJurisdictionId=e.target.value||null;persist();toast(state.currentJurisdictionId?'Location corrected manually':'Location cleared');};$('locateButton').onclick=locate;$('fitMapButton').onclick=()=>{$('mapSvg').setAttribute('viewBox','0 0 1000 620');};$('plateSearch').oninput=render;$('endTripButton').onclick=()=>{const t=trip();if(t&&confirm(`End ${t.name}?`)){t.endedAt=new Date().toISOString();state.activeTrip=null;persist();}};$('exportButton').onclick=exportData;$('clearButton').onclick=()=>{if(confirm('Delete all Plate Quest data?')){localStorage.removeItem(STORAGE_KEY);state=defaults();position=null;persist();}};addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);init();